import CheckoutFooter from "@/components/checkout/CheckoutFooter";
import "../globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Thanh toan",
  description: "Generated by create next app",
};

export default function CheckoutLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body>
        <div className="border-b-1 border-[#C4001F]">
          <h2 className="text-center text-lg font-bold">Trang Thanh Toán</h2>
        </div>
        <main>{children}</main>
        <CheckoutFooter />
      </body>
    </html>
  );
}
