import Header from "@/components/layout/Header";
import StickyMenuBar from "@/components/layout/StickyMenuBar";
import { getMenuCategories } from "@/lib/api/menu";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import FooterComponent from "./footer/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Lyly",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getMenuCategories();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
        <Header categories={categories} />
        {children}
        <FooterComponent />
        <div className="mt-16 lg:hidden">
          <StickyMenuBar />
        </div>
      </body>
    </html>
  );
}
