import Logo from "@/assets/Logo.svg";
import { DrawerCustom } from "@/components/layout/DrawerCustom";
import MenuHeader from "@/components/layout/MenuHeader";
import { SliderTop } from "@/components/layout/SliderTop";
import { Button } from "@/components/ui/button";
import { IFooterData } from "@/lib/types/IFooter";
import { IMeta } from "@/lib/types/IPagination";
import { Input } from "@heroui/input";

import { EyeIcon, ShoppingCart, UserIcon } from "lucide-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import Link from "next/link";
import qs from "qs";
import FooterComponent from "./footer/page";
import "./globals.css";
import axios from "axios";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// interface IFooters {
//   data: {
//     footer_data: IFooterData;
//     // footer_contact:
//   };
//   meta: IMeta;
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const queryFooters = qs.stringify(
  //   {
  //     populate: "*",
  //     pagination: {
  //       page: 1,
  //       pageSize: 6,
  //     },
  //   },
  //   { encode: false }
  // );

  // const response = await axios(`/api/footers?`);
  // const footers: IFooters = response.data;
  // const footerData = Array.isArray(footers.data) ? footers.data[0]?.footer_data : footers.data?.footer_data || null;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="h-9">
          <SliderTop />
        </div>
        <div className="sticky top-0 z-20 bg-white border-b-1 border-[#C4001F]">
          <div className="flex justify-between w-full max-w-[1420px] mx-auto">
            <div className="px-2">
              <Link href={"/"}>
                <Image className="h-14 max-w-24 " src={Logo} alt="" />
              </Link>
            </div>
            <div className="px-2 flex items-center w-[500px]">
              <Input type="search" variant="bordered" radius={"sm"} placeholder="Tìm sản phẩm" />
            </div>
            <div className="px-2 gap-4 flex justify-end items-center">
              <Button variant="black" className="bg-white border border-black lg:flex hidden">
                <UserIcon />
                Tài khoản
              </Button>
              <Button variant="black" className="bg-white border border-black lg:flex hidden">
                <EyeIcon />
                Sản phẩm đã xem
              </Button>
              <ShoppingCart strokeWidth={1} size={28} color="black" />
              <div className="flex lg:hidden">
                <DrawerCustom />
              </div>
            </div>
          </div>
          <div className="max-w-[1420px] pt-4 px-10 mx-auto lg:flex hidden">
            <MenuHeader />
          </div>
        </div>
        {children}
        {/* <FooterComponent footer_data={footerData} /> */}
        <FooterComponent />
      </body>
    </html>
  );
}
