export const searchTrend = {
  data: [
    {
      id: 1,
      documentId: "doc_001",
      title: "Vòng - Lắc",
      createdAt: "2025-04-01T00:00:00Z",
      updatedAt: "2025-04-01T00:00:00Z",
      publishedAt: "2025-04-01T00:00:00Z",
      thumbnail: {
        id: 1,
        documentId: "doc_001",
        name: "vong-lac.jpg",
        alternativeText: "Vòng - Lắc",
        caption: "Vòng - Lắc",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/vong-lac.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "abc123",
            mime: "image/jpeg",
            name: "vong-lac-thumbnail.jpg",
            path: null,
            size: 50,
            width: 200,
            height: 200,
            sizeInBytes: 5000,
          },
        },
        hash: "abc123",
        ext: "jpg",
        mime: "image/jpeg",
        size: 100,
        url: "https://lili.vn/wp-content/uploads/2022/06/Lac-tay-cap-doi-bac-dinh-da-CZ-trai-tim-cua-bien-Erasmus-LILI_199377_3.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-01T00:00:00Z",
        updatedAt: "2025-04-01T00:00:00Z",
        publishedAt: "2025-04-01T00:00:00Z",
      },
      slug: "vong-lac",
    },
    {
      id: 2,
      documentId: "doc_002",
      title: "Nhẫn",
      createdAt: "2025-04-02T00:00:00Z",
      updatedAt: "2025-04-02T00:00:00Z",
      publishedAt: "2025-04-02T00:00:00Z",
      thumbnail: {
        id: 2,
        documentId: "doc_002",
        name: "nhan.jpg",
        alternativeText: "Nhẫn",
        caption: "Nhẫn",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/nhan.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "def456",
            mime: "image/jpeg",
            name: "nhan-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "def456",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://lili.vn/wp-content/uploads/2021/12/Nhan-doi-bac-hiep-si-va-cong-chua-dinh-da-CZ-LILI_819229_1.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      slug: "nhan",
    },
    {
      id: 3,
      documentId: "doc_003",
      title: "Dây Chuyền",
      createdAt: "2025-04-03T00:00:00Z",
      updatedAt: "2025-04-03T00:00:00Z",
      publishedAt: "2025-04-03T00:00:00Z",
      thumbnail: {
        id: 3,
        documentId: "doc_003",
        name: "day-chuyen.jpg",
        alternativeText: "Dây Chuyền",
        caption: "Dây Chuyền",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/day-chuyen.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "ghi789",
            mime: "image/jpeg",
            name: "day-chuyen-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "ghi789",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://lili.vn/wp-content/uploads/2022/09/Day-chuyen-doi-bac-dinh-da-CZ-hinh-ca-voi-va-buom-Brenna-LILI_123985_4.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-03T00:00:00Z",
        updatedAt: "2025-04-03T00:00:00Z",
        publishedAt: "2025-04-03T00:00:00Z",
      },
      slug: "day-chuyen",
    },
    {
      id: 4,
      documentId: "doc_004",
      title: "Bông Tai",
      createdAt: "2025-04-04T00:00:00Z",
      updatedAt: "2025-04-04T00:00:00Z",
      publishedAt: "2025-04-04T00:00:00Z",
      thumbnail: {
        id: 4,
        documentId: "doc_004",
        name: "bong-tai.jpg",
        alternativeText: "Bông Tai",
        caption: "Bông Tai",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/bong-tai.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "jkl012",
            mime: "image/jpeg",
            name: "bong-tai-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "jkl012",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://lili.vn/wp-content/uploads/2022/03/Bong-tai-bac-nu-dinh-da-CZ-co-4-la-LILI_453329_1.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-04T00:00:00Z",
        updatedAt: "2025-04-04T00:00:00Z",
        publishedAt: "2025-04-04T00:00:00Z",
      },
      slug: "bong-tai",
    },
    {
      id: 5,
      documentId: "doc_005",
      title: "Charm Pandora",
      createdAt: "2025-04-05T00:00:00Z",
      updatedAt: "2025-04-05T00:00:00Z",
      publishedAt: "2025-04-05T00:00:00Z",
      thumbnail: {
        id: 5,
        documentId: "doc_005",
        name: "charm-pandora.jpg",
        alternativeText: "Charm Pandora",
        caption: "Charm Pandora",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/charm-pandora.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "mno345",
            mime: "image/jpeg",
            name: "charm-pandora-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "mno345",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://lili.vn/wp-content/uploads/2023/10/Hat-charm-bac-nu-dinh-da-CZ-hinh-cuc-hoa-mi-Eileen-LILI_085652_3.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-05T00:00:00Z",
        updatedAt: "2025-04-05T00:00:00Z",
        publishedAt: "2025-04-05T00:00:00Z",
      },
      slug: "charm-pandora",
    },
    {
      id: 6,
      documentId: "doc_006",
      title: "Khuyên Xỏ",
      createdAt: "2025-04-06T00:00:00Z",
      updatedAt: "2025-04-06T00:00:00Z",
      publishedAt: "2025-04-06T00:00:00Z",
      thumbnail: {
        id: 6,
        documentId: "doc_006",
        name: "khuyen-xo.jpg",
        alternativeText: "Khuyên Xỏ",
        caption: "Khuyên Xỏ",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/khuyen-xo.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "pqr678",
            mime: "image/jpeg",
            name: "khuyen-xo-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "pqr678",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://lili.vn/wp-content/uploads/2021/08/Khuyen-ron-bac-nu-dinh-da-Zircon-LILI_868451_5.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-06T00:00:00Z",
        updatedAt: "2025-04-06T00:00:00Z",
        publishedAt: "2025-04-06T00:00:00Z",
      },
      slug: "khuyen-xo",
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 6,
      pageCount: 1,
      total: 6,
    },
  },
};

export const favoriteProducts = {
  data: [
    {
      id: 1,
      documentId: "LILI_831944",
      title: "Dây chuyền bạc nữ đính đá CZ cả tiên",
      createdAt: "2025-04-02T00:00:00Z",
      updatedAt: "2025-04-02T00:00:00Z",
      publishedAt: "2025-04-02T00:00:00Z",
      slug: "day-chuyen-bac-nu-dinh-da-cz-ca-tien-lili-831944",
      description: "",
      isDiscount: false,
      variants: [
        {
          id: 601,
          color: "Trắng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Trắng",
          price: 726000,
          price_2: 0,
          discount: 0,
          image: {
            id: 101,
            documentId: "image_LILI_453329_trang",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_trang_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang_thumb.jpg",
                path: null,
                size: 10,
                width: 50,
                height: 50,
                sizeInBytes: 10000,
              },
            },
            hash: "hash_bong_tai_trang",
            ext: "jpg",
            mime: "image/jpeg",
            size: 30,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 602,
          color: "Hồng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Hồng",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 102,
            documentId: "image_LILI_453329_hong",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_hong_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong_thumb.jpg",
                path: null,
                size: 12,
                width: 50,
                height: 50,
                sizeInBytes: 12000,
              },
            },
            hash: "hash_bong_tai_hong",
            ext: "jpg",
            mime: "image/jpeg",
            size: 35,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 603,
          color: "Xanh",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Xanh",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 103,
            documentId: "image_LILI_453329_xanh",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_xanh_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh_thumb.jpg",
                path: null,
                size: 11,
                width: 50,
                height: 50,
                sizeInBytes: 11000,
              },
            },
            hash: "hash_bong_tai_xanh",
            ext: "jpg",
            mime: "image/jpeg",
            size: 32,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
      ],
      images: [],
      thumbnail: {
        id: 1,
        documentId: "thumbnail_LILI_831944",
        name: "day-chuyen-bac-nu-dinh-da-cz-ca-tien.jpg",
        alternativeText: null,
        caption: null,
        width: 300,
        height: 300,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            hash: "hash_day_chuyen_bac_nu_thumb",
            mime: "image/jpeg",
            name: "day-chuyen-bac-nu-dinh-da-cz-ca-tien_thumb.jpg",
            path: null,
            size: 30,
            width: 150,
            height: 150,
            sizeInBytes: 30000,
          },
        },
        hash: "hash_day_chuyen_bac_nu",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      related_products: [],
      price: 1023000,
      sub_title: "LILI 831944",
    },
    {
      id: 2,
      documentId: "LILI_335168",
      title: "Nhẫn bạc nữ đính kim cương Moissanite Aidan",
      createdAt: "2025-04-02T00:00:00Z",
      updatedAt: "2025-04-02T00:00:00Z",
      publishedAt: "2025-04-02T00:00:00Z",
      slug: "nhan-bac-nu-dinh-kim-cuong-moissanite-aidan-lili-335168",
      description: "",
      isDiscount: false,
      variants: [
        {
          id: 601,
          color: "Trắng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Trắng",
          price: 726000,
          price_2: 0,
          discount: 0,
          image: {
            id: 101,
            documentId: "image_LILI_453329_trang",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_trang_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang_thumb.jpg",
                path: null,
                size: 10,
                width: 50,
                height: 50,
                sizeInBytes: 10000,
              },
            },
            hash: "hash_bong_tai_trang",
            ext: "jpg",
            mime: "image/jpeg",
            size: 30,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 602,
          color: "Hồng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Hồng",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 102,
            documentId: "image_LILI_453329_hong",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_hong_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong_thumb.jpg",
                path: null,
                size: 12,
                width: 50,
                height: 50,
                sizeInBytes: 12000,
              },
            },
            hash: "hash_bong_tai_hong",
            ext: "jpg",
            mime: "image/jpeg",
            size: 35,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 603,
          color: "Xanh",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Xanh",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 103,
            documentId: "image_LILI_453329_xanh",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_xanh_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh_thumb.jpg",
                path: null,
                size: 11,
                width: 50,
                height: 50,
                sizeInBytes: 11000,
              },
            },
            hash: "hash_bong_tai_xanh",
            ext: "jpg",
            mime: "image/jpeg",
            size: 32,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
      ],
      images: [],
      thumbnail: {
        id: 2,
        documentId: "thumbnail_LILI_335168",
        name: "nhan-bac-nu-dinh-kim-cuong-moissanite-aidan.jpg",
        alternativeText: null,
        caption: null,
        width: 300,
        height: 300,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            hash: "hash_nhan_bac_nu_thumb",
            mime: "image/jpeg",
            name: "nhan-bac-nu-dinh-kim-cuong-moissanite-aidan_thumb.jpg",
            path: null,
            size: 35,
            width: 150,
            height: 150,
            sizeInBytes: 35000,
          },
        },
        hash: "hash_nhan_bac_nu",
        ext: "jpg",
        mime: "image/jpeg",
        size: 130,
        url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      related_products: [],
      price: 1475000,
      sub_title: "LILI 335168",
    },
    {
      id: 3,
      documentId: "LILI_763298",
      title: "Lắc chân bạc nữ đính đá CZ hình cỏ 4 lá Mildred",
      createdAt: "2025-04-02T00:00:00Z",
      updatedAt: "2025-04-02T00:00:00Z",
      publishedAt: "2025-04-02T00:00:00Z",
      slug: "lac-chan-bac-nu-dinh-da-cz-hinh-co-4-la-mildred-lili-763298",
      description: "",
      isDiscount: false,
      variants: [
        {
          id: 601,
          color: "Trắng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Trắng",
          price: 726000,
          price_2: 0,
          discount: 0,
          image: {
            id: 101,
            documentId: "image_LILI_453329_trang",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_trang_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang_thumb.jpg",
                path: null,
                size: 10,
                width: 50,
                height: 50,
                sizeInBytes: 10000,
              },
            },
            hash: "hash_bong_tai_trang",
            ext: "jpg",
            mime: "image/jpeg",
            size: 30,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 602,
          color: "Hồng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Hồng",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 102,
            documentId: "image_LILI_453329_hong",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_hong_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong_thumb.jpg",
                path: null,
                size: 12,
                width: 50,
                height: 50,
                sizeInBytes: 12000,
              },
            },
            hash: "hash_bong_tai_hong",
            ext: "jpg",
            mime: "image/jpeg",
            size: 35,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 603,
          color: "Xanh",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Xanh",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 103,
            documentId: "image_LILI_453329_xanh",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_xanh_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh_thumb.jpg",
                path: null,
                size: 11,
                width: 50,
                height: 50,
                sizeInBytes: 11000,
              },
            },
            hash: "hash_bong_tai_xanh",
            ext: "jpg",
            mime: "image/jpeg",
            size: 32,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
      ],
      images: [],
      thumbnail: {
        id: 3,
        documentId: "thumbnail_LILI_763298",
        name: "lac-chan-bac-nu-dinh-da-cz-hinh-co-4-la-mildred.jpg",
        alternativeText: null,
        caption: null,
        width: 300,
        height: 300,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            hash: "hash_lac_chan_bac_nu_thumb",
            mime: "image/jpeg",
            name: "lac-chan-bac-nu-dinh-da-cz-hinh-co-4-la-mildred_thumb.jpg",
            path: null,
            size: 32,
            width: 150,
            height: 150,
            sizeInBytes: 32000,
          },
        },
        hash: "hash_lac_chan_bac_nu",
        ext: "jpg",
        mime: "image/jpeg",
        size: 125,
        url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      related_products: [],
      price: 1014000,
      sub_title: "LILI 763298",
    },
    {
      id: 4,
      documentId: "LILI_528145",
      title: "Dây chuyền đôi bạc tình yêu tình bạn thân BFF đính đá CZ . Forever Love",
      createdAt: "2025-04-02T00:00:00Z",
      updatedAt: "2025-04-02T00:00:00Z",
      publishedAt: "2025-04-02T00:00:00Z",
      slug: "day-chuyen-doi-bac-tinh-yeu-tinh-ban-than-bff-dinh-da-cz-forever-love-lili-528145",
      description: "",
      isDiscount: false,
      variants: [
        {
          id: 601,
          color: "Trắng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Trắng",
          price: 726000,
          price_2: 0,
          discount: 0,
          image: {
            id: 101,
            documentId: "image_LILI_453329_trang",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_trang_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang_thumb.jpg",
                path: null,
                size: 10,
                width: 50,
                height: 50,
                sizeInBytes: 10000,
              },
            },
            hash: "hash_bong_tai_trang",
            ext: "jpg",
            mime: "image/jpeg",
            size: 30,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 602,
          color: "Hồng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Hồng",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 102,
            documentId: "image_LILI_453329_hong",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_hong_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong_thumb.jpg",
                path: null,
                size: 12,
                width: 50,
                height: 50,
                sizeInBytes: 12000,
              },
            },
            hash: "hash_bong_tai_hong",
            ext: "jpg",
            mime: "image/jpeg",
            size: 35,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 603,
          color: "Xanh",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Xanh",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 103,
            documentId: "image_LILI_453329_xanh",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_xanh_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh_thumb.jpg",
                path: null,
                size: 11,
                width: 50,
                height: 50,
                sizeInBytes: 11000,
              },
            },
            hash: "hash_bong_tai_xanh",
            ext: "jpg",
            mime: "image/jpeg",
            size: 32,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
      ],
      images: [],
      thumbnail: {
        id: 4,
        documentId: "thumbnail_LILI_528145",
        name: "day-chuyen-doi-bac-tinh-yeu-tinh-ban-than-bff-dinh-da-cz-forever-love.jpg",
        alternativeText: null,
        caption: null,
        width: 300,
        height: 300,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            hash: "hash_day_chuyen_doi_thumb",
            mime: "image/jpeg",
            name: "day-chuyen-doi-bac-tinh-yeu-tinh-ban-than-bff-dinh-da-cz-forever-love_thumb.jpg",
            path: null,
            size: 40,
            width: 150,
            height: 150,
            sizeInBytes: 40000,
          },
        },
        hash: "hash_day_chuyen_doi",
        ext: "jpg",
        mime: "image/jpeg",
        size: 140,
        url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      related_products: [],
      price: 2098000,
      sub_title: "LILI 528145",
    },
    {
      id: 5,
      documentId: "LILI_672438",
      title: "Nhẫn cặp đôi bạc đính kim cương Moissanite Theophilus",
      createdAt: "2025-04-02T00:00:00Z",
      updatedAt: "2025-04-02T00:00:00Z",
      publishedAt: "2025-04-02T00:00:00Z",
      slug: "nhan-cap-doi-bac-dinh-kim-cuong-moissanite-theophilus-lili-672438",
      description: "",
      isDiscount: false,
      variants: [
        {
          id: 601,
          color: "Trắng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Trắng",
          price: 726000,
          price_2: 0,
          discount: 0,
          image: {
            id: 101,
            documentId: "image_LILI_453329_trang",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_trang_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-trang_thumb.jpg",
                path: null,
                size: 10,
                width: 50,
                height: 50,
                sizeInBytes: 10000,
              },
            },
            hash: "hash_bong_tai_trang",
            ext: "jpg",
            mime: "image/jpeg",
            size: 30,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 602,
          color: "Hồng",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Hồng",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 102,
            documentId: "image_LILI_453329_hong",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_hong_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-hong_thumb.jpg",
                path: null,
                size: 12,
                width: 50,
                height: 50,
                sizeInBytes: 12000,
              },
            },
            hash: "hash_bong_tai_hong",
            ext: "jpg",
            mime: "image/jpeg",
            size: 35,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
        {
          id: 603,
          color: "Xanh",
          title: "Bông tai bạc nữ đính đá CZ có 4 lá - Xanh",
          price: 759000,
          price_2: 0,
          discount: 0,
          image: {
            id: 103,
            documentId: "image_LILI_453329_xanh",
            name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh.jpg",
            alternativeText: null,
            caption: null,
            width: 100,
            height: 100,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
                hash: "hash_bong_tai_xanh_thumb",
                mime: "image/jpeg",
                name: "bong-tai-bac-nu-dinh-da-cz-co-4-la-xanh_thumb.jpg",
                path: null,
                size: 11,
                width: 50,
                height: 50,
                sizeInBytes: 11000,
              },
            },
            hash: "hash_bong_tai_xanh",
            ext: "jpg",
            mime: "image/jpeg",
            size: 32,
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
        },
      ],
      images: [],
      thumbnail: {
        id: 5,
        documentId: "thumbnail_LILI_672438",
        name: "nhan-cap-doi-bac-dinh-kim-cuong-moissanite-theophilus.jpg",
        alternativeText: null,
        caption: null,
        width: 300,
        height: 300,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
            hash: "hash_nhan_cap_doi_thumb",
            mime: "image/jpeg",
            name: "nhan-cap-doi-bac-dinh-kim-cuong-moissanite-theophilus_thumb.jpg",
            path: null,
            size: 38,
            width: 150,
            height: 150,
            sizeInBytes: 38000,
          },
        },
        hash: "hash_nhan_cap_doi",
        ext: "jpg",
        mime: "image/jpeg",
        size: 135,
        url: "https://lili.vn/wp-content/uploads/2020/11/vong-tay-bac-925-dinh-pha-le-swarovski-1.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      related_products: [],
      price: 1751000,
      sub_title: "LILI 672438",
    },
  ],
};

export const banners = {
  data: [
    {
      id: 1,
      slug: "banner-1",
      image: {
        id: 1,
        documentId: "banner_image_001",
        name: "banner_image_1",
        alternativeText: null,
        caption: null,
        width: 1200,
        height: 600,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://example.com/banner_1_thumb.jpg",
            hash: "img123",
            mime: "image/jpeg",
            name: "banner_1_thumb",
            path: null,
            size: 100,
            width: 300,
            height: 150,
            sizeInBytes: 8000,
          },
        },
        hash: "img123",
        ext: "jpg",
        mime: "image/jpeg",
        size: 200,
        url: "https://lili.vn/wp-content/uploads/2025/03/Banner-San-pham-moi-nhat-PC-chung.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-01T00:00:00Z",
        updatedAt: "2025-04-01T00:00:00Z",
        publishedAt: "2025-04-01T00:00:00Z",
      },
      image_mobile: {
        id: 2,
        documentId: "banner_image_001_mobile",
        name: "banner_image_1_mobile",
        alternativeText: null,
        caption: null,
        width: 600,
        height: 300,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://example.com/banner_1_mobile_thumb.jpg",
            hash: "img456",
            mime: "image/jpeg",
            name: "banner_1_mobile_thumb",
            path: null,
            size: 70,
            width: 150,
            height: 75,
            sizeInBytes: 6000,
          },
        },
        hash: "img456",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://lili.vn/wp-content/uploads/2025/03/Banner-San-pham-moi-nhat-Mobile-chung-1-768x960.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-01T00:00:00Z",
        updatedAt: "2025-04-01T00:00:00Z",
        publishedAt: "2025-04-01T00:00:00Z",
      },
    },
    {
      id: 2,
      slug: "banner-2",
      image: {
        id: 3,
        documentId: "banner_image_002",
        name: "banner_image_2",
        alternativeText: null,
        caption: null,
        width: 1200,
        height: 600,
        formats: {
          thumbnail: {
            ext: "png",
            url: "https://example.com/banner_2_thumb.png",
            hash: "img789",
            mime: "image/png",
            name: "banner_2_thumb",
            path: null,
            size: 120,
            width: 300,
            height: 150,
            sizeInBytes: 10000,
          },
        },
        hash: "img789",
        ext: "png",
        mime: "image/png",
        size: 250,
        url: "https://lili.vn/wp-content/uploads/2023/04/Banner-Top-san-pham-yeu-thich-PC.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      image_mobile: {
        id: 4,
        documentId: "banner_image_002_mobile",
        name: "banner_image_2_mobile",
        alternativeText: null,
        caption: null,
        width: 600,
        height: 300,
        formats: {
          thumbnail: {
            ext: "png",
            url: "https://example.com/banner_2_mobile_thumb.png",
            hash: "img101",
            mime: "image/png",
            name: "banner_2_mobile_thumb",
            path: null,
            size: 100,
            width: 150,
            height: 75,
            sizeInBytes: 8000,
          },
        },
        hash: "img101",
        ext: "png",
        mime: "image/png",
        size: 180,
        url: "https://lili.vn/wp-content/uploads/2023/04/Banner-Top-san-pham-yeu-thich-Mobile-768x960.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 2,
      pageCount: 1,
      total: 2,
    },
  },
};

export const mockFooterData = {
  guides: {
    title: "DỊCH VỤ KHÁCH HÀNG",
    links: [
      { url: "/dieu-khoan-va-dieu-kien", label: "Điều khoản và điều kiện" },
      { url: "/chinh-sach-tra-hang-hoan-tien", label: "Chính sách trả hàng hoàn tiền" },
      { url: "/chinh-sach-giao-hang", label: "Chính sách giao hàng" },
      { url: "/chinh-sach-quyen-rieng-tu", label: "Chính sách quyền riêng tư" },
      { url: "/huong-dan-mua-hang-online", label: "Hướng dẫn mua hàng online" },
    ],
  },
  contact_info: {
    title: "CẨM NANG SỬ DỤNG",
    links: [
      { url: "/tai-sao-nen-chon-bac-cao-cap", label: "Tại sao nên chọn bạc cao cấp?" },
      { url: "/cach-lam-trang-bac-tai-nha", label: "Cách làm trắng bạc tại nhà" },
      { url: "/phan-biet-cac-loai-bac-s925-s999", label: "Phân biệt các loại bạc S925, S999,..." },
      { url: "/nhung-tac-dung-cua-bac", label: "Những tác dụng của bạc" },
      { url: "/cach-bao-quan-trang-suc-bac", label: "Cách bảo quản trang sức bạc" },
    ],
  },
  general_info: {
    title: "THÔNG TIN CHUNG",
    links: [
      { url: "/tin-trang-suc", label: "Tin trang sức" },
      { url: "/quyen-loi-thanh-vien", label: "Quyền lợi thành viên" },
      { url: "/tiep-thi-lien-ket-lili", label: "Tiếp thị liên kết Lili" },
      { url: "/uu-dai-khi-danh-gia", label: "Ưu đãi khi đánh giá" },
      { url: "/nhan-qua-tri-an", label: "Nhận quà tri ân" },
      { url: "/lien-he", label: "Liên hệ" },
    ],
  },
  feedback_section: {
    title: "Ý KIẾN ĐÓNG GÓP",
    button_url: "/gui-y-kien",
    button_text: "GỬI Ý KIẾN",
    description:
      "Lili luôn mong nhận được ý kiến đóng góp từ bạn để nâng cấp dịch vụ và sản phẩm tốt hơn. Nếu bạn có ý kiến, đừng ngần ngại đóng góp cho Lili nhé. Lili xin cảm ơn!",
  },
};
