import { IBanner } from "../types/IBanner";
import { IMeta } from "../types/IPagination";
import { IProduct } from "../types/IProduct";
import { ISearchTrend } from "../types/ISearchTrend";

interface ISearchTrends {
  data: ISearchTrend[];
  meta: IMeta;
}

export const searchTrend = {
  data: [
    {
      id: 1,
      documentId: "doc_001",
      title: "Vòng - Lắc",
      createdAt: "2025-04-01T00:00:00Z",
      updatedAt: "2025-04-01T00:00:00Z",
      publishedAt: "2025-04-01T00:00:00Z",
      thumbnail: {
        id: 1,
        documentId: "doc_001",
        name: "vong-lac.jpg",
        alternativeText: "Vòng - Lắc",
        caption: "Vòng - Lắc",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/vong-lac.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "abc123",
            mime: "image/jpeg",
            name: "vong-lac-thumbnail.jpg",
            path: null,
            size: 50,
            width: 200,
            height: 200,
            sizeInBytes: 5000,
          },
        },
        hash: "abc123",
        ext: "jpg",
        mime: "image/jpeg",
        size: 100,
        url: "/images/vong-lac.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-01T00:00:00Z",
        updatedAt: "2025-04-01T00:00:00Z",
        publishedAt: "2025-04-01T00:00:00Z",
      },
      slug: "vong-lac",
    },
    {
      id: 2,
      documentId: "doc_002",
      title: "Nhẫn",
      createdAt: "2025-04-02T00:00:00Z",
      updatedAt: "2025-04-02T00:00:00Z",
      publishedAt: "2025-04-02T00:00:00Z",
      thumbnail: {
        id: 2,
        documentId: "doc_002",
        name: "nhan.jpg",
        alternativeText: "Nhẫn",
        caption: "Nhẫn",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/nhan.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "def456",
            mime: "image/jpeg",
            name: "nhan-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "def456",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "/images/nhan.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      slug: "nhan",
    },
    {
      id: 3,
      documentId: "doc_003",
      title: "Dây Chuyền",
      createdAt: "2025-04-03T00:00:00Z",
      updatedAt: "2025-04-03T00:00:00Z",
      publishedAt: "2025-04-03T00:00:00Z",
      thumbnail: {
        id: 3,
        documentId: "doc_003",
        name: "day-chuyen.jpg",
        alternativeText: "Dây Chuyền",
        caption: "Dây Chuyền",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/day-chuyen.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "ghi789",
            mime: "image/jpeg",
            name: "day-chuyen-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "ghi789",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "/images/day-chuyen.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-03T00:00:00Z",
        updatedAt: "2025-04-03T00:00:00Z",
        publishedAt: "2025-04-03T00:00:00Z",
      },
      slug: "day-chuyen",
    },
    {
      id: 4,
      documentId: "doc_004",
      title: "Bông Tai",
      createdAt: "2025-04-04T00:00:00Z",
      updatedAt: "2025-04-04T00:00:00Z",
      publishedAt: "2025-04-04T00:00:00Z",
      thumbnail: {
        id: 4,
        documentId: "doc_004",
        name: "bong-tai.jpg",
        alternativeText: "Bông Tai",
        caption: "Bông Tai",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/bong-tai.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "jkl012",
            mime: "image/jpeg",
            name: "bong-tai-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "jkl012",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "/images/bong-tai.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-04T00:00:00Z",
        updatedAt: "2025-04-04T00:00:00Z",
        publishedAt: "2025-04-04T00:00:00Z",
      },
      slug: "bong-tai",
    },
    {
      id: 5,
      documentId: "doc_005",
      title: "Charm Pandora",
      createdAt: "2025-04-05T00:00:00Z",
      updatedAt: "2025-04-05T00:00:00Z",
      publishedAt: "2025-04-05T00:00:00Z",
      thumbnail: {
        id: 5,
        documentId: "doc_005",
        name: "charm-pandora.jpg",
        alternativeText: "Charm Pandora",
        caption: "Charm Pandora",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/charm-pandora.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "mno345",
            mime: "image/jpeg",
            name: "charm-pandora-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "mno345",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "/images/charm-pandora.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-05T00:00:00Z",
        updatedAt: "2025-04-05T00:00:00Z",
        publishedAt: "2025-04-05T00:00:00Z",
      },
      slug: "charm-pandora",
    },
    {
      id: 6,
      documentId: "doc_006",
      title: "Khuyên Xỏ",
      createdAt: "2025-04-06T00:00:00Z",
      updatedAt: "2025-04-06T00:00:00Z",
      publishedAt: "2025-04-06T00:00:00Z",
      thumbnail: {
        id: 6,
        documentId: "doc_006",
        name: "khuyen-xo.jpg",
        alternativeText: "Khuyên Xỏ",
        caption: "Khuyên Xỏ",
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "/images/khuyen-xo.jpg", // Đặt đường dẫn ảnh trong thư mục public
            hash: "pqr678",
            mime: "image/jpeg",
            name: "khuyen-xo-thumbnail.jpg",
            path: null,
            size: 60,
            width: 200,
            height: 200,
            sizeInBytes: 6000,
          },
        },
        hash: "pqr678",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "/images/khuyen-xo.jpg", // Đặt đường dẫn ảnh trong thư mục public
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-06T00:00:00Z",
        updatedAt: "2025-04-06T00:00:00Z",
        publishedAt: "2025-04-06T00:00:00Z",
      },
      slug: "khuyen-xo",
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 6,
      pageCount: 1,
      total: 6,
    },
  },
};

interface IProducts {
  data: IProduct[];
  meta: IMeta;
}

export const favoriteProducts: IProducts = {
  data: [
    {
      id: 1,
      documentId: "product_001",
      title: "Product 1",
      createdAt: "2025-04-01T00:00:00Z",
      updatedAt: "2025-04-01T00:00:00Z",
      publishedAt: "2025-04-01T00:00:00Z",
      slug: "product-1",
      description: "Description of Product 1",
      isDiscount: true,
      variants: [
        {
          id: 1,
          color: "Red",
          title: "Variant 1",
          price: 100,
          price_2: 90,
          discount: 10,
          image: {
            id: 1,
            documentId: "image_001",
            name: "variant_1_image",
            alternativeText: null,
            caption: null,
            width: 300,
            height: 300,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://example.com/variant_1_thumb.jpg",
                hash: "xyz789",
                mime: "image/jpeg",
                name: "variant_1_thumb",
                path: null,
                size: 50,
                width: 150,
                height: 150,
                sizeInBytes: 4000,
              },
            },
            hash: "xyz789",
            ext: "jpg",
            mime: "image/jpeg",
            size: 100,
            url: "https://example.com/variant_1_image.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-01T00:00:00Z",
            updatedAt: "2025-04-01T00:00:00Z",
            publishedAt: "2025-04-01T00:00:00Z",
          },
        },
      ],
      images: [
        {
          id: 1,
          documentId: "image_001",
          name: "product_1_image",
          alternativeText: null,
          caption: null,
          width: 500,
          height: 500,
          formats: {
            thumbnail: {
              ext: "jpg",
              url: "https://example.com/product_1_thumb.jpg",
              hash: "abc123",
              mime: "image/jpeg",
              name: "product_1_thumb",
              path: null,
              size: 70,
              width: 200,
              height: 200,
              sizeInBytes: 5000,
            },
          },
          hash: "abc123",
          ext: "jpg",
          mime: "image/jpeg",
          size: 150,
          url: "https://example.com/product_1_image.jpg",
          previewUrl: null,
          provider: "local",
          provider_metadata: null,
          createdAt: "2025-04-01T00:00:00Z",
          updatedAt: "2025-04-01T00:00:00Z",
          publishedAt: "2025-04-01T00:00:00Z",
        },
      ],
      thumbnail: {
        id: 1,
        documentId: "product_001",
        name: "product_1_thumbnail",
        alternativeText: null,
        caption: null,
        width: 200,
        height: 200,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://example.com/product_1_thumb.jpg",
            hash: "abc123",
            mime: "image/jpeg",
            name: "product_1_thumb",
            path: null,
            size: 50,
            width: 200,
            height: 200,
            sizeInBytes: 5000,
          },
        },
        hash: "abc123",
        ext: "jpg",
        mime: "image/jpeg",
        size: 100,
        url: "https://example.com/product_1_thumbnail.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-01T00:00:00Z",
        updatedAt: "2025-04-01T00:00:00Z",
        publishedAt: "2025-04-01T00:00:00Z",
      },
      related_products: [
        {
          id: 2,
          documentId: "product_002",
          title: "Product 2",
          createdAt: "2025-04-02T00:00:00Z",
          updatedAt: "2025-04-02T00:00:00Z",
          publishedAt: "2025-04-02T00:00:00Z",
          slug: "product-2",
          description: "Description of Product 2",
          isDiscount: false,
          variants: [],
          images: [],
          thumbnail: {
            id: 2,
            documentId: "product_002",
            name: "product_2_thumbnail",
            alternativeText: null,
            caption: null,
            width: 200,
            height: 200,
            formats: {
              thumbnail: {
                ext: "jpg",
                url: "https://example.com/product_2_thumb.jpg",
                hash: "def456",
                mime: "image/jpeg",
                name: "product_2_thumb",
                path: null,
                size: 60,
                width: 200,
                height: 200,
                sizeInBytes: 5500,
              },
            },
            hash: "def456",
            ext: "jpg",
            mime: "image/jpeg",
            size: 120,
            url: "https://example.com/product_2_thumbnail.jpg",
            previewUrl: null,
            provider: "local",
            provider_metadata: null,
            createdAt: "2025-04-02T00:00:00Z",
            updatedAt: "2025-04-02T00:00:00Z",
            publishedAt: "2025-04-02T00:00:00Z",
          },
          related_products: [],
          price: 120,
          sub_title: "Sub title for Product 2",
        },
      ],
      price: 100,
      sub_title: "Sub title for Product 1",
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 2,
      pageCount: 1,
      total: 2,
    },
  },
};

interface IBanners {
  data: IBanner[];
  meta: IMeta;
}

export const banners: IBanners = {
  data: [
    {
      id: 1,
      slug: "banner-1",
      image: {
        id: 1,
        documentId: "banner_image_001",
        name: "banner_image_1",
        alternativeText: null,
        caption: null,
        width: 1200,
        height: 600,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://example.com/banner_1_thumb.jpg",
            hash: "img123",
            mime: "image/jpeg",
            name: "banner_1_thumb",
            path: null,
            size: 100,
            width: 300,
            height: 150,
            sizeInBytes: 8000,
          },
        },
        hash: "img123",
        ext: "jpg",
        mime: "image/jpeg",
        size: 200,
        url: "https://example.com/banner_1_image.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-01T00:00:00Z",
        updatedAt: "2025-04-01T00:00:00Z",
        publishedAt: "2025-04-01T00:00:00Z",
      },
      image_mobile: {
        id: 2,
        documentId: "banner_image_001_mobile",
        name: "banner_image_1_mobile",
        alternativeText: null,
        caption: null,
        width: 600,
        height: 300,
        formats: {
          thumbnail: {
            ext: "jpg",
            url: "https://example.com/banner_1_mobile_thumb.jpg",
            hash: "img456",
            mime: "image/jpeg",
            name: "banner_1_mobile_thumb",
            path: null,
            size: 70,
            width: 150,
            height: 75,
            sizeInBytes: 6000,
          },
        },
        hash: "img456",
        ext: "jpg",
        mime: "image/jpeg",
        size: 120,
        url: "https://example.com/banner_1_mobile_image.jpg",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-01T00:00:00Z",
        updatedAt: "2025-04-01T00:00:00Z",
        publishedAt: "2025-04-01T00:00:00Z",
      },
    },
    {
      id: 2,
      slug: "banner-2",
      image: {
        id: 3,
        documentId: "banner_image_002",
        name: "banner_image_2",
        alternativeText: null,
        caption: null,
        width: 1200,
        height: 600,
        formats: {
          thumbnail: {
            ext: "png",
            url: "https://example.com/banner_2_thumb.png",
            hash: "img789",
            mime: "image/png",
            name: "banner_2_thumb",
            path: null,
            size: 120,
            width: 300,
            height: 150,
            sizeInBytes: 10000,
          },
        },
        hash: "img789",
        ext: "png",
        mime: "image/png",
        size: 250,
        url: "https://example.com/banner_2_image.png",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
      image_mobile: {
        id: 4,
        documentId: "banner_image_002_mobile",
        name: "banner_image_2_mobile",
        alternativeText: null,
        caption: null,
        width: 600,
        height: 300,
        formats: {
          thumbnail: {
            ext: "png",
            url: "https://example.com/banner_2_mobile_thumb.png",
            hash: "img101",
            mime: "image/png",
            name: "banner_2_mobile_thumb",
            path: null,
            size: 100,
            width: 150,
            height: 75,
            sizeInBytes: 8000,
          },
        },
        hash: "img101",
        ext: "png",
        mime: "image/png",
        size: 180,
        url: "https://example.com/banner_2_mobile_image.png",
        previewUrl: null,
        provider: "local",
        provider_metadata: null,
        createdAt: "2025-04-02T00:00:00Z",
        updatedAt: "2025-04-02T00:00:00Z",
        publishedAt: "2025-04-02T00:00:00Z",
      },
    },
  ],
  meta: {
    pagination: {
      page: 1,
      pageSize: 2,
      pageCount: 1,
      total: 2,
    },
  },
};

export const mockFooterData = {
  guides: {
    title: "DỊCH VỤ KHÁCH HÀNG",
    links: [
      { url: "/dieu-khoan-va-dieu-kien", label: "Điều khoản và điều kiện" },
      { url: "/chinh-sach-tra-hang-hoan-tien", label: "Chính sách trả hàng hoàn tiền" },
      { url: "/chinh-sach-giao-hang", label: "Chính sách giao hàng" },
      { url: "/chinh-sach-quyen-rieng-tu", label: "Chính sách quyền riêng tư" },
      { url: "/huong-dan-mua-hang-online", label: "Hướng dẫn mua hàng online" },
    ],
  },
  contact_info: {
    title: "CẨM NANG SỬ DỤNG",
    links: [
      { url: "/tai-sao-nen-chon-bac-cao-cap", label: "Tại sao nên chọn bạc cao cấp?" },
      { url: "/cach-lam-trang-bac-tai-nha", label: "Cách làm trắng bạc tại nhà" },
      { url: "/phan-biet-cac-loai-bac-s925-s999", label: "Phân biệt các loại bạc S925, S999,..." },
      { url: "/nhung-tac-dung-cua-bac", label: "Những tác dụng của bạc" },
      { url: "/cach-bao-quan-trang-suc-bac", label: "Cách bảo quản trang sức bạc" },
    ],
  },
  general_info: {
    title: "THÔNG TIN CHUNG",
    links: [
      { url: "/tin-trang-suc", label: "Tin trang sức" },
      { url: "/quyen-loi-thanh-vien", label: "Quyền lợi thành viên" },
      { url: "/tiep-thi-lien-ket-lili", label: "Tiếp thị liên kết Lili" },
      { url: "/uu-dai-khi-danh-gia", label: "Ưu đãi khi đánh giá" },
      { url: "/nhan-qua-tri-an", label: "Nhận quà tri ân" },
      { url: "/lien-he", label: "Liên hệ" },
    ],
  },
  feedback_section: {
    title: "Ý KIẾN ĐÓNG GÓP",
    button_url: "/gui-y-kien",
    button_text: "GỬI Ý KIẾN",
    description:
      "Lili luôn mong nhận được ý kiến đóng góp từ bạn để nâng cấp dịch vụ và sản phẩm tốt hơn. Nếu bạn có ý kiến, đừng ngần ngại đóng góp cho Lili nhé. Lili xin cảm ơn!",
  },
};
